### ISSUE TITLE
Build breaks with recent libvips version

### ISSUE THREAD

**Issue by scossu** [harvard-lts/kakadu-vips#23]
libvips version: 8.17.2-1
Kakadu version: 8.4.1

Compiler output: 
```
$ make 
g++ -shared -fPIC  `pkg-config vips --cflags` -I/usr/local/src/kakadu/v8_4_1-02108C/managed/all_includes  -c -o kakadu-vips.o kakadu-vips.cpp
g++ -shared -fPIC  `pkg-config vips --cflags` -I/usr/local/src/kakadu/v8_4_1-02108C/managed/all_includes  -c -o kakaduload.o kakaduload.cpp
g++ -shared -fPIC  `pkg-config vips --cflags` -I/usr/local/src/kakadu/v8_4_1-02108C/managed/all_includes  -c -o kakadusave.o kakadusave.cpp
kakadusave.cpp: In function ‘void vips_foreign_save_kakadu_class_init(VipsForeignSaveKakaduClass*)’:
kakadusave.cpp:501:32: error: cannot convert ‘VipsSaveable’ to ‘VipsForeignSaveable’ in assignment
  501 |         save_class->saveable = VIPS_SAVEABLE_ANY;
      |                                ^~~~~~~~~~~~~~~~~
      |                                |
      |                                VipsSaveable
make: *** [<builtin>: kakadusave.o] Error 1
```

This used to compile with libvips 8.15.1. It looks like it may be an internal API change, what do you think @jcupitt ?

**Comment by jcupitt** [comment]
Hi @scossu,

`VipsSaveable` has been deprecated and replaced by `VipsForeignSaveable`. By default, libvips disables deprecated code, but you can reneable it with `-Ddeprecated=true` during configure. 

So ... as a workaround, I would add `-Ddeprecated=true` to your `meson setup`. For a better fix, I'll make a PR to update kakadu-save to the latest API version.

**Comment by jcupitt** [comment]
Oh wait, now I test, it looks like the deprecated fallback code in libvips for `VipsSaveable` isn't working, sigh. 

I'll make a kakadu-vips PR, and another for libvips to fix the deprecated path there.

**Comment by kleisauke** [comment]
As a workaround for `-Ddeprecated=false`, you could do:
```diff
--- a/src/kakadu.h
+++ b/src/kakadu.h
@@ -36,6 +36,11 @@ G_STMT_END
 #define VIPS_META_BITS_PER_SAMPLE "bits-per-sample"
 #endif
 
+// libvips 8.17 compatibility
+#ifndef VIPS_SAVEABLE_ANY
+#define VIPS_SAVEABLE_ANY VIPS_FOREIGN_SAVEABLE_ANY
+#endif
+
 extern const char *vips__kakadu_suffs[];
 
 // object init
```
(untested)

**Comment by jcupitt** [comment]
I've been removed from this repo so I can't easily make a PR, but the diff is just:

```diff
diff --git a/CHANGELOG.md b/CHANGELOG.md
index aae1276..2a1f4a2 100644
--- a/CHANGELOG.md
+++ b/CHANGELOG.md
@@ -3,6 +3,7 @@
 ## master
 
 - improve handling of kakadu errors
+- update to latest libvips API
 
 ## 2024/4/4 1.0
 
diff --git a/src/kakadusave.cpp b/src/kakadusave.cpp
index 1e3b271..c27eb41 100644
--- a/src/kakadusave.cpp
+++ b/src/kakadusave.cpp
@@ -509,7 +509,7 @@ vips_foreign_save_kakadu_class_init(VipsForeignSaveKakaduClass *klass)
 
        foreign_class->suffs = vips__kakadu_suffs;
 
-       save_class->saveable = VIPS_SAVEABLE_ANY;
+       save_class->saveable = VIPS_FOREIGN_SAVEABLE_ANY;
 
        VIPS_ARG_STRING(klass, "options", 11,
         _("Options"),
```

**Comment by jcupitt** [comment]
Thanks for reporting this, @scossu
